### ISSUE TITLE
Question: All google modules required?

### ISSUE THREAD

**Issue by wiesson** [Strayer/django-gcloud-storage#11]
It's just a question, when I run `pip install django-gcloud-storage` like every google-cloud tool will be installed. How could I reduce that? :) 

So my django requirement file grows from 27 dependencies to 79 😱

**Comment by Strayer** [comment]
The docs are not very clear on this, but it should be possible: https://cloud.google.com/python/setup#install_the_google_cloud_client_library_for_python

The tests should make this fairly easy, feel free to submit a PR!

**Comment by wiesson** [comment]
Thanks for quick reply! I will take a look at the docs and figure out if I could submit a PR.
