### ISSUE TITLE
unable to initialize cloud sql instance

### ISSUE THREAD

**Issue by pranayyy** [Strayer/django-gcloud-storage#12]
Has per the documentation [https://cloud.google.com/python/django/flexible-environment#initialize_your_cloud_sql_instance] i am going step by step process but at initalization cloud_sql_proxy.exe -instances="[YOUR_INSTANCE_CONNECTION_NAME]"=tcp:5432....i` am confused and not able to execute...getting error.plz elaborate

**Comment by Strayer** [comment]
I don't see how this is related to this project. Please try contacting Google Cloud support or relevant mailing lists/StackOverflow.
