### ISSUE TITLE
cannot import name SpooledTemporaryFile

### ISSUE THREAD

**Issue by learner-01** [Strayer/django-gcloud-storage#14]
I have a django project which is going to be hosted in AppEngine.
I tried using django-gcloud-storage to save file to GCS.
When I run the app locally via manager.py, I dont get any error. My file is being uploaded to bucket as well.
But If I run the app either via dev_appserver or deployed version in GAE, I get the below error:
```python
cannot import name SpooledTemporaryFile
```
The page containing the form wont open and keeps on giving this error.
kindly help

**Comment by Strayer** [comment]
That sounds very strange – sounds like something is wrong with the environment. Are you sure GAE is running on Python 2.7+? SpooledTemporaryFile doesn't exist in Python 2.6, maybe that is the problem.

**Comment by learner-01** [comment]
I am using Python 2.7.12
It seems like GAE doesn't have Spooled File in its library.
I copied contents from google.appengine.ext.tempfile to my own module & in django-storages I changed SpooledFile class to my custom Class according to environment.

Its working now in both manage.py and deployed app.
But dev_appserver gives Connection Error(13 - Permission denied)

**Comment by Strayer** [comment]
Glad that you found a fix! I don't have any experience with GAE, so I won't be able to help you there, seems like a GAE-specific issue.

A quick Google search resulted in this: https://stackoverflow.com/questions/32318905/workaround-for-dev-appserver-py-inability-to-make-ssl-requests
Maybe that is the problem.

**Comment by learner-01** [comment]
I am not using any braintree module a of now.
Till now its purely django with cloud sql.

I will see what to do.. thanks for the help. :)
