### ISSUE TITLE
The content type is not set

### ISSUE THREAD

**Issue by tokibito** [Strayer/django-gcloud-storage#17]
Content type is not set for the file uploaded to Cloud Storage.

I need to pass the content_type parameter to the Blob.upload_from_file method, what should I do?

**Comment by asbjorn** [comment]
Hi.

I have the same issue. Uploading images and the Content-Type gets set to `application/octet-stream`.

**Comment by Strayer** [comment]
This should be fixed by https://github.com/Strayer/django-gcloud-storage/pull/18 and is released in version 0.4.0.
