### ISSUE TITLE
Django 4 incompatibility due to "from django.utils.encoding import force_text", should be easy to fix

### ISSUE THREAD

**Issue by bixbyr** [strayer/django-gcloud-storage#22]
The use of force_text is deprecated in Django 4.0, see https://stackoverflow.com/questions/70382084/import-error-force-text-from-django-utils-encoding

I found it used here in the project: https://github.com/strayer/django-gcloud-storage/blob/master/django_gcloud_storage/__init__.py#L16

I think it is as simple as replacing this with force_str

**Comment by strayer** [comment]
Hey @bixbyr, thank you for reporting this and your friendly email. I'll be looking into this in the next days and report back to you.

**Comment by bixbyr** [comment]
Thank you very much, it would help a lot.

**Comment by terada-mariana** [comment]
@strayer 
https://github.com/strayer/django-gcloud-storage/pull/23

Hi, could you check this PR?
It's for Django4 support.

When do you think the next release would be approximately?

**Comment by bixbyr** [comment]
It seems to work in Django 4 :-)

How soon would you able to release a version with the changes?

**Comment by strayer** [comment]
Hey everyone. Thanks @terada-mariana for the PR. I'll handle this this week, but can't give any promises. I'm doing this in my spare time and got a lot of stuff on my desk. :(

**Comment by strayer** [comment]
Hey @bixbyr, @terada-mariana 

I just uploaded v0.5.0 to PyPI: https://pypi.org/project/django-gcloud-storage/0.5.0/

Please let me know if you face any issues!
